version: 2
 

  # run_jest_tests:
  #   docker:
  #     - image: circleci/node:10.16.3
  #     - image: mongo:4.2.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: update-npm
  #         command: 'sudo npm install -g npm@5'
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #     - run:
  #         name: install-npm-wee
  #         command: npm install
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #         paths:
  #           - ./node_modules
  #     - run:
  #         name: install jest
  #         command:
  #           npm install @salesforce/sfdx-lwc-jest --save-dev
  #     - run:
  #         name: run jest tests
  #         command:
  #           npm run test:unit
  #     - store_artifacts:
  #         path: test-results.xml
  #         prefix: tests
  #     - store_test_results:
  #         path: test-results.xml
jobs:
run_apex_tests:
    docker:
     - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: login into devhub
          command: |
             mkdir keys
             echo $SFDX_JWT_KEY | xxd -r -ps >> keys/hub.key
             openssl rsa -in keys/hub.key -check -noout
             sfdx force:auth:jwt:grant --clientid $SFDX_CONSUMER_KEY --jwtkeyfile keys/hub.key --username $HUB_SFDC_USER --setdefaultdevhubusername -a hub
      - run:
          name: create scratch org
          command:
            sfdx force:org:create -s -f config/project-scratch-def.json -a circle_build_$CIRCLE_BUILD_NUM
      - run:
          name: push source to scratch org
          command:
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
      - run:
          name: create user for role
          command:
            sfdx force:user:create --definitionfile scripts/user-def.json
      - run:
          name: run configuration apex
          command:
            sfdx force:apex:execute -f scripts/ciconfig.apex
      - run:
          name: run apex tests
          command: |
            mkdir -p tests/junit
            sfdx force:apex:test:run 
      - store_test_results:
          path: tests/junit
      - store_artifacts:
          path: tests/junit
      - run:
          name: delete scratch org
          when: always
          command: |
            sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p
workflows:
  version: 2
  apex_tests-beta_package-release:
    jobs:
      # - run_jest_tests
      - run_apex_tests:
          # requires:
          #   - run_jest_tests
      - deploy_beta:
          requires:
            - run_apex_tests
          filters:
            branches:
              only: /release\/.*/
      - hold_before_build_beta:
          type: approval
          requires:
            - deploy_beta
          filters:
            branches:
              only: /release\/.*/
      - build_beta:
          requires:
            - hold_before_build_beta
          filters:
            branches:
              only: /release\/.*/
      - install_beta_for_test:
          requires:
            - build_beta
          filters:
            branches:
              only: /release\/.*/
      - hold_before_build_managed:
          type: approval
          requires:
            - build_beta
          filters:
            branches:
              only:
                - /release\/.*/
            tags:
              only:
                - /v[0-9]+(\.[0-9]+)+/
      - create_managed_package:
          requires:
            - hold_before_build_managed
          filters:
            branches:
              only:
                - /release\/.*/
            tags:
              only:
                - /v[0-9]+(\.[0-9]+)+/
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:latest
#     steps:
#       - checkout
#       - run:
#           name: The First Step - install sfdx
#           command: |
#             echo 'Hello World!'
#             echo 'This is the delivery pipeline'
#             ls -al
#             npm install sfdx-cli
#             node_modules/sfdx-cli/bin/run --version
#             node_modules/sfdx-cli/bin/run plugins --core 
#       - run:
#           name: login into devhub
#           command:
#             # //mkdir keys
#             # //echo $SFDX_JWT_KEY | xxd -r -ps >> keys/hub.key
#             # //openssl rsa -in keys/hub.key -check -noout
#                 node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid 3MVG91BJr_0ZDQ4sKOWsrBpEmM_cNBfeSjgz1d7SAHDVOfeq6dnxGXpaW2w9RVpYfPpZDD8Khch4nj0mqtQCc 
#                 --jwtkeyfile /Users/Asif/JWT/server.key --username siflearnsalesforce@salesforce.com 
#                --setdefaultdevhubusername --setalias my-hub-org
           
#       - run:
#           name: convert source and deploy it to target org
#           command: |
#             mkdir output
#             node_modules/sfdx-cli/bin/run force:source:convert -d output/
#             node_modules/sfdx-cli/bin/run force:mdapi:deploy -d output/ -u hub -w 100
#       - run:
#           name: run apex classes
#           command: |
#             node_modules/sfdx-cli/bin/run force:apex:test:run -u hub -c -r human