# jobs:
#     build:
#         macos:
#             xcode: 11.3.0
#         run_jest_tests:
#             docker:
#                 - image: circleci/node:10.16.3
#                 - image: mongo:4.2.0
#             steps:
#                 - checkout
#                 - run:
#                       name: update-npm
#                       command: 'sudo npm install -g npm@5'
#                 - restore_cache:
#                       key: dependency-cache-{{ checksum "package-lock.json" }}
#                 - run:
#                       name: install-npm-wee
#                       command: npm install
#                 - save_cache:
#                       key: dependency-cache-{{ checksum "package-lock.json" }}
#                       paths:
#                           - ./node_modules
#                 - run:
#                       name: install jest
#                       command: npm install @salesforce/sfdx-lwc-jest --save-dev
#                 - run:
#                       name: run jest tests
#                       command: npm run test:unit
#                 - store_artifacts:
#                       path: test-results.xml
#                       prefix: tests
#                 - store_test_results:
#                       path: test-results.xml
#         run_apex_tests:
#             # docker:
#             #   - image: appsolutely/sfdx_circleci_container:latest
#             steps:
#                 - checkout
#                 - run:
#                       name: login into devhub
#                       command: |
#                           mkdir keys
#                           echo $SFDX_JWT_KEY | xxd -r -ps >> keys/hub.key
#                           openssl rsa -in keys/hub.key -check -noout
#                           sfdx force:auth:jwt:grant --clientid $SFDX_CONSUMER_KEY --jwtkeyfile keys/hub.key --username $HUB_SFDC_USER --setdefaultdevhubusername -a hub
#                 - run:
#                       name: create scratch org
#                       command: sfdx force:org:create -s -f config/project-scratch-def.json -a circle_build_$CIRCLE_BUILD_NUM
#                 - run:
#                       name: push source to scratch org
#                       command: sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
#                 # - run:
#                 #       name: run apex tests
#                 #       command: |
#                 #           mkdir -p tests/junit
#                 #           sfdx force:apex:test:run -d tests/junit -r junit --tests SurveyControllerTest,AnswerGenerationTest
#                 - store_test_results:
#                       path: tests/junit
#                 - store_artifacts:
#                       path: tests/junit
#                 - run:
#                       name: delete scratch org
#                       when: always
#                       command: |
#                           sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p

jobs:
    install_authenticate:
        executor: sfdx/default
        steps:
            - checkout
            - sfdx/install
            - sfdx/auth:
                  defaultusername: $HUB_SFDC_USER
            - run:
                  command: >
                      echo You now have access to the sfdx cli and may execute commands
                      against it.

                      sfdx force:auth:list
                  name: Run your SFDX commands here
orbs:
    salesforce-sfdx: circleci/salesforce-sfdx@1.0.0
version: 2.1
workflows:
    basic-test:
        jobs:
            - install_authenticate
