version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: The First Step - install sfdx
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ls -al
            npm install sfdx-cli
            node_modules/sfdx-cli/bin/run --version
            node_modules/sfdx-cli/bin/run plugins --core 
      - run:
          name: login into devhub
          command:
            # //mkdir keys
            # //echo $SFDX_JWT_KEY | xxd -r -ps >> keys/hub.key
            # //openssl rsa -in keys/hub.key -check -noout
                node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid 3MVG91BJr_0ZDQ4sKOWsrBpEmM_cNBfeSjgz1d7SAHDVOfeq6dnxGXpaW2w9RVpYfPpZDD8Khch4nj0mqtQCc \
                --jwtkeyfile /Users/Asif/JWT/server.key --username siflearnsalesforce@salesforce.com \
               --setdefaultdevhubusername --setalias my-hub-org
           
      - run:
          name: convert source and deploy it to target org
          command: |
            mkdir output
            node_modules/sfdx-cli/bin/run force:source:convert -d output/
            node_modules/sfdx-cli/bin/run force:mdapi:deploy -d output/ -u hub -w 100
      - run:
          name: run apex classes
          command: |
            node_modules/sfdx-cli/bin/run force:apex:test:run -u hub -c -r human